// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCltVV9rOplltqVL7ttLxZGulu8XBpngek',
    appId: '1:135254931319:web:6f7447b083ec5b1c089372',
    messagingSenderId: '135254931319',
    projectId: 'wastator-capstone',
    authDomain: 'wastator-capstone.firebaseapp.com',
    databaseURL: 'https://wastator-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'wastator-capstone.appspot.com',
    measurementId: 'G-6J5S5CZ5PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XKMjuCxBSlx63fylpSKu095BqSQllnQ',
    appId: '1:135254931319:android:5b4deb019f4ed5c3089372',
    messagingSenderId: '135254931319',
    projectId: 'wastator-capstone',
    databaseURL: 'https://wastator-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'wastator-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYBcF1PJAFFAwW_-4LFKzN15ACpBLPIg',
    appId: '1:135254931319:ios:a36dfa60bcbfbb36089372',
    messagingSenderId: '135254931319',
    projectId: 'wastator-capstone',
    databaseURL: 'https://wastator-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'wastator-capstone.appspot.com',
    iosBundleId: 'com.example.wastator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYBcF1PJAFFAwW_-4LFKzN15ACpBLPIg',
    appId: '1:135254931319:ios:a36dfa60bcbfbb36089372',
    messagingSenderId: '135254931319',
    projectId: 'wastator-capstone',
    databaseURL: 'https://wastator-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'wastator-capstone.appspot.com',
    iosBundleId: 'com.example.wastator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCltVV9rOplltqVL7ttLxZGulu8XBpngek',
    appId: '1:135254931319:web:98b60194573fb43a089372',
    messagingSenderId: '135254931319',
    projectId: 'wastator-capstone',
    authDomain: 'wastator-capstone.firebaseapp.com',
    databaseURL: 'https://wastator-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'wastator-capstone.appspot.com',
    measurementId: 'G-2YGD0DH4VV',
  );
}
